import "./globals.css";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Job Manager",
  description: "Generated by create next app",
  icons: "favicon.ico",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
